@startuml

title Diagramme de séquence : Consulter l'historique des visites
hide footbox

actor "Professionnel" as pro

participant "_: HistoriqueVue " as df
pro -> df : consulterHistoriqueVisite()
activate df
    participant "_: HistoriqueControleur" as dc
    df -> dc : afficherVisites()
    activate dc
    participant "_: Session" as d
    dc -> d : getVisites()
    activate d
    participant "_: Dossier" as dsr
        d -> dsr : getVisites()
        activate dsr
        dsr --> d : visites
        deactivate dsr
    d --> dc : visites
    deactivate d
    create participant "historiqueVisiteVue: VisiteHistoriqueVue" as vhf
    dc -> vhf: this(visites)
    activate vhf
    loop visite in visites
        create participant "ligneVisite: LigneVisiteVue" as lvf
            vhf -> lvf : this(visite)
            activate lvf
            lvf --> vhf : ligneVisite
            deactivate lvf
        vhf -> vhf : ajouterLigne(ligneVisite)
    end
    vhf --> dc : historiqueVisiteVue
    deactivate vhf
    dc --> df : historiqueVisiteVue
    deactivate dc
    df --> pro : historiqueVisiteVue
deactivate df

pro -> lvf : afficherDetail()
activate lvf
create participant "visiteVue: VisiteVue" as vf
    lvf -> vf: this(visite)
    deactivate lvf
    activate vf
    vf --> pro 
    deactivate vf

@enduml