@startuml

class Patient {
    - nom : String 
    - prenom : String
    - dateNaissance : Date 
    - villeNaissance : String
    - noAssurance : String
    + getCoordonnees() : Coordonnees
}

class Coordonnees {
    - adresse : String
    - telephone : String
    - courriel : String
}

enum Genre {
    MASCULIN
    FEMININ
    AUTRE
}

class Dossier {
    + getVisites() : List<Visite>
    + getAntecedents() : List<Antecedent>
    + getTraitements() : List<Traitement>
}

class Visite {
    - date : Date
    - resume : String
    - notes : List<String>
    + getTraitement () : Traitement
}

class Antecedent {
    - debut : Date
    - fin : Date [0..1]
}

class Diagnostic {
    - description : String
}

class Traitement {
    - description : String
}

class Medecin {
    - nom : String 
    - prenom : String
    - permis : String
    - specialite : String
}

class Etablissement {
    - id : String
    - description : String
}

class Utilisateur { 
    - username : String 
    - password : String 
    } 

Interface SourceDonnees {
    
}

interface Recherchable {
    + findbyId(id : String) : Optional<T>
    + findbyUsernameAndPassword (username : String, password: String) : Optional<T>
}

class SourceDonneesImplem {
    + ^findbyId(id : String) : Optional<Dossier>
    + ^findbyUsernameAndPassword (username : String, password: String) : Optional<Utilisateur>
}

class Session {
    + telechargerDossier(noAss : String)
    + getVisites() : List<Visite>
    + getAntecedents() : List<Antecedent>
    + getTraitements() : List<Traitement>
}

interface authentifiable {
    + login(user: String, pass: String) : boolean
}

class ConnexionVue {
}

class ConnexionControleur {
    - validerSaisie()
    + seConnecter()
}

class PatientVue{

}

class HistoriqueVue {

}

class PatientControleur {
    + afficherPatient()
}

class HistoriqueControleur {
    + afficherVisites()
    + afficherAntecedents()
    + afficherTraitements()
}

class Main {
    + {static} main (args : String[])
}

Patient *--> "1\ncoordonnées" Coordonnees
Patient #--> "0..2\nparents" Patient
Patient #--> "1\ngenre" Genre

Dossier *--> "*\nvisites" Visite
Dossier *--> "*\nantécédents" Antecedent
Dossier *---> "1\npatient" Patient

Visite *--> "0..1\ndiagnostic" Diagnostic
Visite *--> "0..1\ntraitement" Traitement
Visite #--> "1\nmedecin" Medecin

Antecedent #--> "1\ntraitant" Medecin
Antecedent #--> "1\diagnostic" Diagnostic
Antecedent #--> "1\ntraitement" Traitement

Medecin #--> "1\netablissement" Etablissement

Session *--> "0..1\ndossier" Dossier

Session -> SourceDonnees

Session *--> "0..1\nutilisateur" Utilisateur 
Session .l.|> authentifiable

SourceDonnees  .|> Recherchable
SourceDonnees <|.. SourceDonneesImplem

ConnexionVue -- ConnexionControleur
PatientVue --PatientControleur
HistoriqueVue -- HistoriqueControleur 

ConnexionControleur #--> Session
PatientControleur #--> Session
HistoriqueControleur #--> Session


ConnexionVue <.. Main
Main .> ConnexionControleur
Main ..> Session

@enduml