@startuml
node telephoneAndroid <<device>> {
 artifact dossierMedical.apk <<application Android>>
}

node telephoneiOS <<device>> {
 artifact dossierMedical.ipa <<application iOS>>
}

node PcProfessionnel <<device>> {
 node lecteurPuceCarteP <<device>>
 artifact consulterDossierProfessionel.jar <<artifact>>

}

node PcMedecin <<device>> {
 node lecteurPuceCarteM <<device>>
 artifact gestionDossierMedecin.jar <<artifact>>

}

node PcRAMQ <<device>> {
 artifact consulterDossierRamq.jar <<artifact>>

}

node PcPatient <<device>> {
    component NagivateurWeb <<component>>
}


node serveurBD <<device>> {
 database SQLite3 <<database>>
}

node serveurWeb <<device>> {
 artifact siteWeb <<artifact>>
}


PcPatient -r-> serveurWeb
serveurWeb -> serveurBD

telephoneAndroid -l- serveurBD
telephoneiOS -l- serveurBD

PcProfessionnel -u-> serveurBD
PcMedecin -u-> serveurBD
PcRAMQ -u-> serveurBD




@enduml