@startuml
title Diagramme de séquence : Reconstituer dossier par modification
hide footbox
actor "RAMQ" as ramq
-> ramq: ReconstituerDossierModification
activate ramq
hide footbox
ramq -> Session: findById()
activate Session
Session -> SourceDonneesImplem: findById()
activate SourceDonneesImplem
database Bd as "bd"
activate Bd
SourceDonneesImplem -> Bd: findById()
alt introuvable
Bd --> SourceDonneesImplem: error()
else patient trouvé
Bd --> SourceDonneesImplem:List<Dossier>
end
deactivate Bd
SourceDonneesImplem --> Session: List<Dossier>
deactivate SourceDonneesImplem
alt modification trouvée
Session -> Session: findByModification()
Session --> ramq: Dossier
else introuvable
Session --> ramq: error()
deactivate Session
deactivate ramq
end

@enduml