@startuml

title Diagramme de sequence : Reconstituer un dossier par modification
hide footbox
Actor "RAMQ" as ramq

hide footbox
ramq -> Main: reconstituerDossierModification(id , modification)
activate Main
Main -> SourceDonnees: findByIdAndModification(id , modification)
activate SourceDonnees
database Bd as "bd"
activate Bd
SourceDonnees ->> Bd: requete
alt introuvable
Bd --> SourceDonnees: error
SourceDonnees --> Main: error
Main --> ramq: error
else patient trouvé
Bd --> SourceDonnees: dossierJson
deactivate Bd
SourceDonnees --> Main: dossierJson
deactivate SourceDonnees
Main --> ramq: dossierJson
deactivate Main
end

@enduml