@startuml
title Diagramme de sequence : Reconstituer dossier par modification
hide footbox
Actor "RAMQ" as ramq
activate ramq
hide footbox
ramq -> Main: reconstituerDossierModification()
activate Main
Main -> SourceDonnees: findByIdAndModification()
activate SourceDonnees
database Bd as "bd"
activate Bd
SourceDonnees -> Bd: requete
alt introuvable
Bd --> SourceDonnees: error()
SourceDonnees --> Main: error()
Main --> ramq: error()
else patient trouvé
Bd --> SourceDonnees:JSON:Dossier
deactivate Bd
SourceDonnees -> Main: JSON:Dossier
Main -> ramq: JSON:Dossier
end
deactivate SourceDonnees

deactivate Main
deactivate ramq

@enduml