@startuml
title Diagramme de sequence : Reconstituer dossier par date
hide footbox
Actor "RAMQ" as ramq

hide footbox
ramq -> Main: reconstituerDossierDate(id , date)
activate Main
Main -> SourceDonnees: findByIdAndDate(id , date)
activate SourceDonnees
database Bd as "bd"
activate Bd
SourceDonnees -> Bd: requete
alt introuvable
Bd --> SourceDonnees: error
SourceDonnees --> Main: error
Main --> ramq: error
else patient trouvé
Bd --> SourceDonnees: dossierJson
deactivate Bd
SourceDonnees --> Main: dossierJson
deactivate SourceDonnees
Main --> ramq: dossierJson
deactivate Main
end




@enduml