@startuml


title Diagramme de séquence : Créer un dossier pour un nouvel assuré

hide footbox

actor RAMQ as ramq

participant "_: Main" as main
participant "_: SourceDonnees" as sd
database "Bd" as bd

ramq -> main : informationsPatientJson
    activate main 
    main -> sd : creerDossier(informationsPatientJson )
    activate sd 
    sd ->> bd : requete
    
    alt requete ok
        sd --> main : true
        main --> ramq : succes
    else requete erreur
        sd --> main : false
        deactivate sd
        main --> ramq : erreur
        deactivate main
    end


@enduml