@startuml
title Diagramme de séquence : Créer un dossier
actor "Base de Données RAMQ" as ram
ram -> Session: informationPatient
activate Session

opt antecedents.exists
Session -> Antecedents: this(debut,fin)
activate Antecedents
Antecedents --> Session: Antecedents
deactivate Antecedents
end
create participant "Nouvelle Visite: Visite" as Visite
Session -> Visite: this(Date,resume,note)
activate Visite
Visite --> Session: Visite
deactivate Visite
Session -> Patient: getCoordonnees()
activate Patient
Patient -> Coordonnees: getCoordonnees()
activate Coordonnees
Coordonnees --> Patient: Coordonnees
deactivate Coordonnees
Patient --> Session: Coordonnees
deactivate Patient
create participant "Nouveau Dossier: Dossier" as doss
alt Antecedent.exists
Session --> doss: this(Antecedent,Visite, Coordonnees)
activate doss
else aucun antecedent
Session --> doss: this(Visite, Coordonnees)
end
doss --> Session: Dossier
deactivate doss
Session -> Session: enregistrerDossier()
hidefootbox 

@enduml