@startuml

title Diagramme de séquence : Consulter les antecedents
hide footbox

actor "Professionnel" as pro

participant "_: HistoriqueVue " as hv
pro -> hv : consulterAntecedents()
activate hv
    participant "_: HistoriqueControleur" as hc
    hv -> hc : afficherAntecedents()
    activate hc
    participant "_: Session" as ssn
    hc -> ssn : getAntecedents()
    activate ssn
        participant "_: Dossier" as dsr
        ssn -> dsr : getAntecedents()
        activate dsr
        dsr --> ssn : antecedents
        deactivate dsr
    ssn --> hc : antecedents
    deactivate ssn
    create participant "listeAntecedents: ListAntecedentsVue" as laf
    hc -> laf: this(antecedents)
    activate laf
    loop antecedent in antecedents
        create participant "ligneAntecedent: LigneAntecedentVue" as lf
            laf -> lf : this(antecedent)
            activate lf
            lf --> laf : ligneAntecedent
            deactivate lf
        laf -> laf : ajouterLigne(ligneAntecedent)
    end
    laf --> hc : listeAntecedents
    deactivate laf
    hc --> hv : listeAntecedents
    deactivate hc
    hv --> pro : listeAntecedents
deactivate hv

pro -> lf : afficherDetail()
activate lf
create participant "antecedentVue: AntecedentVue" as af
    lf -> af: this(antecedent)
    deactivate lf
    activate af
    af --> pro 
    deactivate af

@enduml