@startuml

' classes model

class Dossier {
    + ajouterVisite(visite : Visite)
    + AjouterAntecedent (antecedent : Antecedent)
    + getVisites() : List<Visite>
    + getAntecedents() : List<Antecedent>
    + getTraitements() : List<Traitement>
}

class Visite {
    - date : Date
    - resume : String
    - notes : List<String>
    + setResume (resume: String)
    + ajouterDiagnostic(dg: Diagnostic)
    + ajouterTraitement(trt: Traitement)
    + ajouterNote(note: String)
    + supprimerDiagnostic(dg: Diagnostic)
    + supprimerTraitement(trt: Traitement)
    + supprimerNote(note: String)
}


class Antecedent {
    - debut : Date
    - fin : Date [0..1]
    + setDebut(date : Date)
    + setFin(date : Date)
    + setDiagnostic()
    + setTraitement()
}

class HistoriqueTraitement {

}

class Diagnostic {
    - description : String
}

class Traitement {
    - description : String
    - debut : Date
    - fin : Date [0..1]
}

class Medecin {
    - nom : String 
    - prenom : String
    - permis : String
    - specialite : String
    - etablissement : String
}

' classes IHM
class DossierControleur {
    + getVisites() : List<Visite>
    + getAntecedents() : List<Antecedent>
    + getTraitements() : List<Traitement>
    + ajouterVisite(visite : Visite)
}

class PrincipaleFrame {
    + consulterHistoriqueVisite()
    + consulterAntecedents()
    + consulterTraitements()
}

class VisiteHistoriqueFrame {
    + this(vistes : List<Visite>)
}

class LigneVisiteFrame {
    + this(visite : Visite)
    + afficherDetail()
}

class VisiteFrame {
    + this(visite : Visite)
}

class NouvelleVisiteFrame {
    
}

class ListeAntecedentsFrame {
    + this(antecedents : List<Antecedent>)
}

class LigneAntecedentFrame {
    + this(antecedent : Antecedent)
    + afficherDetail()
}

class AntecedentFrame {
    + this(antecedent : Antecedent)
}

class AntecedentModificationFrame {

}

class NouvelAntecedentFrame {
    
}

class LigneAntecedentModificationFrame {

}

class ListeTraitementFrame {
    + this(traitements : List<Traitement>)
}

class LigneTraitementFrame {
    + this(traitement : Traitement)
}

' associations

Dossier *--> "*\nvisites" Visite
Dossier *--> "*\nantécédents" Antecedent

Visite *--> "*\ndiagnostic" Diagnostic
Visite *--> "*\ntraitement" Traitement
Visite #--> "1\nmedecin" Medecin

Antecedent #--> "1\ntraitant" Medecin
Antecedent #--> "1\diagnostic" Diagnostic
Antecedent #--> "*\ntraitements" HistoriqueTraitement
HistoriqueTraitement #--> "*\ntraitement" Traitement
HistoriqueTraitement #--> "1\nprescripteur" Medecin

PrincipaleFrame --> DossierControleur
DossierControleur --> Dossier

PrincipaleFrame *-->"0..1\nvisites" VisiteHistoriqueFrame
PrincipaleFrame *--> "0..1\nnouvelleVisite"NouvelleVisiteFrame
PrincipaleFrame *--> "0..1\nantecedents"ListeAntecedentsFrame
PrincipaleFrame *--> "0..1\nnouvelAntededent"NouvelAntecedentFrame
PrincipaleFrame *--> "0..1\ntraitement"ListeTraitementFrame



VisiteHistoriqueFrame *--> "*\nlignes" LigneVisiteFrame
ListeAntecedentsFrame *--> "*\nlignes" LigneAntecedentFrame
LigneAntecedentFrame <|-  LigneAntecedentModificationFrame
AntecedentFrame <|- AntecedentModificationFrame 
ListeTraitementFrame *--> "*\nlignes" LigneTraitementFrame


LigneVisiteFrame *--> "0..1\ndetail"VisiteFrame
NouvelleVisiteFrame --> NouvelAntecedentFrame
NouvelleVisiteFrame --> ListeAntecedentsFrame
LigneAntecedentFrame *--> "0..1\ndetail"AntecedentFrame
LigneAntecedentModificationFrame *--> "0..1\ndetail"AntecedentModificationFrame

LigneAntecedentFrame #--> Antecedent
AntecedentFrame #--> Antecedent
LigneVisiteFrame #--> Visite
VisiteFrame #--> Visite
LigneTraitementFrame #-->Traitement
NouvelleVisiteFrame *--> Visite


DossierControleur <- NouvelleVisiteFrame
DossierControleur <-- NouvelAntecedentFrame
DossierControleur <-- AntecedentModificationFrame


@enduml