@startuml

title Diagramme de séquence : Consulter l'historique des visites
hide footbox

actor "Professionnel" as pro

participant "_: PrincipaleFrame " as df
pro -> df : consulterHistoriqueVisite()
activate df
    participant "_: DossierControleur" as dc
    df -> dc : getVisites()
    activate dc
    participant "_: Dossier" as d
    dc -> d : getVisites()
    activate d
    d --> dc : visites
    deactivate d
    dc --> df : visites
    deactivate dc
    create participant "historiqueVisite: VisiteHistoriqueFrame" as vhf
    df -> vhf: this(visites)
    activate vhf
    loop visite in visites
        create participant "ligneVisite: LigneVisiteFrame" as lvf
            vhf -> lvf : this(visite)
            activate lvf
            lvf --> vhf : ligneVisite
            deactivate lvf
        vhf -> vhf : ajouterLigne(ligneVisite)
    end
    vhf --> df : historiqueVisite
    deactivate vhf
    df --> pro : historiqueVisite
deactivate df

pro -> lvf : afficherDetail()
activate lvf
create participant "visiteFrame: VisiteFrame" as vf
    lvf -> vf: this(visite)
    deactivate lvf
    activate vf
    vf --> pro 
    deactivate vf


@enduml