@startuml

title Diagramme de séquence : Consulter l'historique des visites
hide footbox

actor "Professionnel" as pro

participant "_: HistoriqueVue " as df
pro -> df : consulterTraitements()
activate df
    participant "_: HistoriqueControleur" as dc
    df -> dc : afficherTraitements()
    activate dc
    participant "_: Session" as d
    dc -> d : getTraitements()
    activate d
    participant "_: Dossier" as dsr
        d -> dsr : getTraitements()
        activate dsr
        dsr --> d : traitements
        deactivate dsr
    d --> dc : traitements
    deactivate d
    create participant "listeTraitementsVue: ListeTraitementsVue" as vhf
    dc -> vhf: this(traitements)
    activate vhf
    loop traitement in traitements
        create participant "ligneTraitement: LigneTraitementVue" as lvf
            vhf -> lvf : this(traitement)
            activate lvf
            lvf --> vhf : ligneTraitement
            deactivate lvf
        vhf -> vhf : ajouterLigne(ligneTraitement)
    end
    vhf --> dc : listeTraitementsVue
    deactivate vhf
    dc --> df : listeTraitementsVue
    deactivate dc
    df --> pro : listeTraitementsVue
deactivate df

@enduml